# Generated by Django 5.2 on 2025-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0003_add_email_logo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='tema_primario',
            field=models.CharField(default='azul', max_length=100),
        ),
    ]
