# Generated by Django 5.2.2 on 2025-06-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="usar_tls",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
