# Generated by Django 5.2.2 on 2025-06-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracao", "0002_configuracaosistema_usar_tls"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="tempo_sessao",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
