# Generated by Django 5.2.2 on 2025-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracao", "0004_configuracaosistema_tentativas_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="tempo_bloqueio",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
