# Generated by Django 5.2.2 on 2025-06-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracao", "0005_configuracaosistema_tempo_bloqueio"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosistema",
            name="requer_senha_forte",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
