# Generated by Django 5.2 on 2025-07-11 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("cor", models.CharField(default="#6c757d", max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "codigo_barras",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Código de Barras",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                (
                    "preco_custo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "margem_lucro",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "despesas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "impostos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("estoque", models.IntegerField(default=0)),
                ("estoque_minimo", models.IntegerField(default=5)),
                (
                    "unidade_medida",
                    models.CharField(default="UN", max_length=10, verbose_name="Unidade de Medida"),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Peso em kg",
                        max_digits=8,
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="produtos.categoriaproduto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["descricao"],
            },
        ),
        migrations.CreateModel(
            name="MovimentoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("saida", "Saída"),
                            ("ajuste", "Ajuste de Inventário"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("estoque_anterior", models.IntegerField()),
                ("estoque_atual", models.IntegerField()),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Número do Pedido, NF",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento de Estoque",
                "verbose_name_plural": "Movimentos de Estoque",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoPreco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco_custo_anterior",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "preco_custo_novo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_venda_anterior",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "preco_venda_novo",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "margem_anterior",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("margem_nova", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_alteracao", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_precos",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Preço",
                "verbose_name_plural": "Histórico de Preços",
                "ordering": ["-data_alteracao"],
            },
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["descricao"], name="produtos_pr_descric_7d60b7_idx"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["categoria"], name="produtos_pr_categor_b0e6ca_idx"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["ativo"], name="produtos_pr_ativo_3694bc_idx"),
        ),
    ]
