# Generated by Django 5.2 on 2025-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
