# Generated by Django 5.2 on 2025-06-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
