# Generated by Django 5.2 on 2025-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "comissao_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Comissão (%) sobre o valor dos produtos vendidos",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
