# Generated by Django 5.2 on 2025-07-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicopedido",
            name="status_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Pendente"),
                    ("A", "Aprovado"),
                    ("B", "Embalado para Envio"),
                    ("E", "Enviado"),
                    ("T", "Entregue"),
                    ("D", "Devolução"),
                    ("R", "Reenviar"),
                    ("C", "Cancelado"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicopedido",
            name="status_novo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Pendente"),
                    ("A", "Aprovado"),
                    ("B", "Embalado para Envio"),
                    ("E", "Enviado"),
                    ("T", "Entregue"),
                    ("D", "Devolução"),
                    ("R", "Reenviar"),
                    ("C", "Cancelado"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pendente"),
                    ("A", "Aprovado"),
                    ("B", "Embalado para Envio"),
                    ("E", "Enviado"),
                    ("T", "Entregue"),
                    ("D", "Devolução"),
                    ("R", "Reenviar"),
                    ("C", "Cancelado"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
