# Generated by Django 5.2 on 2025-06-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_cupomdesconto_pedido_cupom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexopedido',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='historicopedido',
            options={'ordering': ['-data']},
        ),
    ]
