# Generated by Django 5.2 on 2025-06-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_anexopedido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido do cliente', max_digits=10),
        ),
    ]
