# Generated by Django 5.2 on 2025-07-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("pedidos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Centro de Custo",
                "verbose_name_plural": "Centros de Custo",
            },
        ),
        migrations.CreateModel(
            name="FluxoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(unique=True)),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "entradas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saidas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "saldo_final",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fluxo de Caixa",
                "verbose_name_plural": "Fluxo de Caixa",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("data", models.DateField()),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True,
                        help_text="Data de vencimento para contas a receber",
                        null=True,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("pedido", "Venda de Pedido"),
                            ("servico", "Prestação de Serviços"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("debito", "Cartão Débito"),
                            ("credito", "Cartão Crédito"),
                            ("transferencia", "Transferência"),
                            ("boleto", "Boleto"),
                            ("cheque", "Cheque"),
                        ],
                        default="dinheiro",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pendente"),
                            ("R", "Realizado"),
                            ("C", "Cancelado"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "anexo",
                    models.FileField(blank=True, null=True, upload_to="financeiro/anexos/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pedido relacionado a esta receita",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pedidos.pedido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("data", models.DateField()),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True,
                        help_text="Data de vencimento para contas a pagar",
                        null=True,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("devolucao", "Devolução"),
                            ("fornecedor", "Fornecedor"),
                            ("marketing", "Marketing"),
                            ("operacional", "Operacional"),
                            ("administrativo", "Administrativo"),
                            ("impostos", "Impostos"),
                            ("outros", "Outros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("debito", "Cartão Débito"),
                            ("credito", "Cartão Crédito"),
                            ("transferencia", "Transferência"),
                            ("boleto", "Boleto"),
                            ("cheque", "Cheque"),
                        ],
                        default="dinheiro",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pendente"),
                            ("R", "Realizado"),
                            ("C", "Cancelado"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "anexo",
                    models.FileField(blank=True, null=True, upload_to="financeiro/anexos/"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "centro_custo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.centrocusto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-data"],
                "indexes": [
                    models.Index(fields=["data"], name="financeiro__data_54ed3b_idx"),
                    models.Index(fields=["categoria"], name="financeiro__categor_5d32be_idx"),
                    models.Index(fields=["status"], name="financeiro__status_b6512e_idx"),
                ],
            },
        ),
    ]
