# Generated by Django 5.2 on 2025-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
