# Generated by Django 5.2 on 2025-06-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos_por_real', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('valor_por_ponto', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('pontos_minimos_resgate', models.IntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='pontos_fidelidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='programa_fidelidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.programafidelidade'),
        ),
    ]
