# Generated by Django 5.2.2 on 2025-06-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_programafidelidade_cliente_pontos_fidelidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dep',
            field=models.CharField(blank=True, help_text='Departamento', max_length=10, null=True, verbose_name='DEP'),
        ),
    ]
