# Generated by Django 5.2.2 on 2025-06-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dep',
        ),
    ]
